spring:
  datasource:
    url: jdbc:h2:mem:expenses-portal;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security: 
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      issuer: expense-portal
      expiration: 86400000 # onde day in milliseconds
  erp-integration:
    endpoints:
      register-person: http://localhost:8080/erp/person
      update-person: http://localhost:8080/erp/person/
      register-expense: http://localhost:8080/erp/expense